### PR TITLE
Publisher

### PR DESCRIPTION
**Pull request by jasonfine**
Note that this was branched from https://github.com/wearefine/fae/tree/92566-security-updates to get the new Docker/testing setup from Jay.

### CODE REVIEW

**Review by jclemans — APPROVED** [review]
This looks awesome 👍

**Comment by aaronransley** [comment]
suggest: update PR title to reflect Publish -> Deploy verbiage change

**Comment by jasonfine** [comment]
@jamesmk do not merge till further notice, seeing some things using this branch in a real-world app that might need to be addressed here, stay tuned.

**Comment by jasonfine** [comment]
@jamesmk confirmed clear to merge

**Pull request merged**
