### PR TITLE
Fixes #432 - Create association on locale change

### LINKED ISSUE #432: Locale is being ignored for content blocks with multi lang support
What I have in `I18n.locale` is being ignored and the first/default language content is always fetched. 

Rails 5.1, fae-rails 2.0.0

```ruby
# config/initializers/fae.rb

Fae.setup do |config|
  config.languages = {
    en: 'English',
    cs: 'Česky'
  }
end
```

```ruby
# app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :set_locale

  def home
    @item = HomePage.instance
  end

  private

  def set_locale
    I18n.locale = params[:locale] ||
                  request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first.presence ||
                  I18n.default_locale
  end
end
```

```ruby
# app/models/home_page.rb
class HomePage < Fae::StaticPage

  @slug = 'home'

  # required to set the has_one associations, Fae::StaticPage will build these associations dynamically
  def self.fae_fields
    {
      main_title: { type: Fae::TextField, languages: Fae.languages.keys },
      subtitle: { type: Fae::TextField, languages: Fae.languages.keys }
    }
  end
end
```

The locale is set up correctly, but I always get the incorrect content:

It must be some kind of noob error, could anyone point me to what I am doing wrong please?

### PR DESCRIPTION
**Pull request by xprazak2**
According to the docs, calling MyPage.instance.header
should get the header text for current locale.
However, the associations are set up in a singleton
for a default locale and never modified.

The language-specific methods like MyPage.instance.header_en
still work, but it would be nice to have fae handle the locale
for us.

This change checks for languages in fae_fields for page
and dynamically changes the association if the locale change
is detected.

### CODE REVIEW

**Comment by xprazak2** [comment]
There is no way I can reasonably satisfy code climate - if I use the guard clause, then I get flagged for the line length.

**Comment by johnnyshields** [comment]
I would suggest to remove the singleton altogether. Does it really add a substantial performance benefit?

**Comment by xprazak2** [comment]
I removed the singleton as suggested.

**Comment by xprazak2** [comment]
Fixing tests, can't get around the line length/guard clause rules combo.

**Comment by jamesmk** [comment]
@xprazak2 I'm sorry if the docs weren't clear, but auto-translating attrs is provided by the `fae_translate` method (https://github.com/wearefine/fae/blob/65a4cb2304969e0ffcf58290b7b3cd0a415c7e69/app/models/concerns/fae/base_model_concern.rb#L66). This method doesn't currently support `Fae::StaticPage`.

The `@singleton_is_setup` is crucial for performance reasons, otherwise all the methods would have to be redefined every time you request an instance. So the meta programming can't change based on `I18n.locale`.

However, it would be possible to omit the base attr name here and then layer on a dynamic method similar to `fae_translate`. So `Fae::StaticPage` would define `header_en` and `header_cs` and layed on top would be something like:

```ruby
translated_attributes.each do |attribute|
  define_method attribute.to_s do
    self.send "#{attribute}_#{I18n.locale}"
  end
end
```

I'm going to close out this and open a ticket. I do like the refactoring  you made in the model, so if you want to include that or and attempt at the above, I'll make it a priority.

thanks!

**Comment by xprazak2** [comment]
Adding `fae_translate :field_name` to static page as described in https://github.com/wearefine/fae/pull/472 works flawlessly, thanks!

**Pull request closed without merging**
