### PR TITLE
Upload images through the markdown editor

### PR DESCRIPTION
**Pull request by y-chiasson**
#260

### CODE REVIEW

**Comment by y-chiasson** [comment]
You can put the following code in a .sh file and execute it to create example app.
Then go to http://localhost:3000/admin/articles/new to try the markdown editor


```
rails _4.2.9_ new markdown_example_app && cd markdown_example_app
echo "gem 'fae-rails', git: 'git://github.com/buysell-technologies/fae.git', branch: 'upstream-issue#260'" >> ./Gemfile
bundle install
bundle exec rails g fae:install

rails g fae:scaffold Article title:string body:text
rake db:migrate
rake fae:seed_db

cat <<EOF > ./app/views/admin/articles/_form.html.slim 
= simple_form_for(['admin', @item]) do |f|
  header.content-header.js-content-header
    == render 'fae/shared/form_header', header: @klass_name
  == render 'fae/shared/errors'

  main.content
    = fae_input f, :title
    = fae_input f, :body, as: :text, markdown: true

EOF

# rails s
# http://localhost:3000/admin/articles/new
```

**Comment by y-chiasson** [comment]
@jamesmk Thank you for having a look at this PR. I will commit some documentation and tests as soon as possible!

**Comment by christophebeling** [comment]
How is the progress here? We could really need this feature! If there is something i could help with feel free to get in touch with we :)

**Comment by jamesmk** [comment]
@christophebeling This feature is missing documentation and tests. If you are interested in contributing @y-chiasson might accept a PR into their `upstream-issue#260` branch?

**Comment by christophebeling** [comment]
@jamesmk what kind of tests did you think of? do you use any javascript testing framework yet? documentation dosen't look that tough since this feature is pretty easy to use. but testing all the new javascript might be a lot of work

**Comment by jamesmk** [comment]
@christophebeling We don't have a dedicated JS testing frameworks, but you can test JS interactions via our acceptance testing framework, Capybara. I'm looking for a test emulating a successful interaction with the feature. 

We don't use the WYSIWYG internally, so we rely on tests to keep the less visible features stable. The more the merrier :)

**Comment by johnnyshields** [comment]
👍 for getting this in the next release

**Comment by johnnyshields** [comment]
What's the status of this?

**Comment by abejosua** [comment]
How can I use this?

**Comment by jamesmk** [comment]
@johnnyshields I have requested some tests along with the PR. As soon as someone adds them, I'll be happy to merge.

@abejosua You can point Fae to @y-chiasson's branch in your `Gemfile`. However, you will no longer receive bugfixes and features from the main Gem. Bonus points: you could fork it and adds tests to this PR and then it will be a part of Fae core ;)

**Comment by johnnyshields** [comment]
Can someone at FINE get this to the finish line? We've been using it in production for half a year without issue.

**Pull request merged**
