### PR TITLE
add travisbuddy

### PR DESCRIPTION
**Pull request by jamesmk**
...and fails specs for testing

### CODE REVIEW

**Comment by jamesmk** [comment]
@jasonfine @aaronransley @cpitkin @tshedor @LeChin Thoughts on this integration? ☝️

**Comment by cpitkin** [comment]
This seems a little redundant with the integrations that Github already offers. I suppose it is nice to have the logs right in the comment stream and it is an easy way to let the person know that they broke the tests.

**Comment by jamesmk** [comment]
@cpitkin Yeah, I'm feeling like it's unnecessary. Everyone has a link to travis to view the errors and it's just extra noise in the comments.

**Comment by jamesmk** [comment]
Yeah, not feeling this...

**Comment by tshedor** [comment]
Wanted to throw my two cents in, in case the maintainers of Travis Buddy see this. Travis does such a nice job of making their interface approachable with rotating, smiling caricatures (the people with the hardware hats). It softens the miserable experience of combing through a stack trace. 

The Travis Buddy avatar, in contrast, grimaces "You broke my repo, you dolt." It recalls the decal of the kid peeing on stuff that commonly plastered on pickup truck windows. At best, he's that one guy who was never without a Tech Deck and wouldn't hesitate to remind that his tricks were way cooler than yours.

**Pull request closed without merging**
